### ISSUE TITLE
Actualizar documentación ESP32

### ISSUE THREAD

**Issue by Bichuno** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-07#9]

**Comment by valmarios** [comment]
Producto: NodeMcu ESP-WROOM-32S Wifi + Bluetooth 4.2 IoT

SKU: 1501

Esta placa de desarrollo te permite hacer proyectos con la plataforma ESP32. Tiene WiFi y Bluetooth 4.2 gracias al procesador doble nucleo Tensilica Xtensa LX6. La plataforma ESP32 ofrece WiFi, Bluetooth y BLE. Tiene un CPU de dos nucleos de hasta 240Mhz que se pueden controlar independientemente. Ademas integra internamente una gran cantidad de perifericos incluyendo: sensores tactiles capacitivos, sensor de efecto Hall, amplificadores de bajo ruido, interfaz para tarjeta SD, Ethernet, SPI de alta velocidad, UART y I2S e I2C.

Especificaciones:
- Voltaje de Alimentacion: 5V (USB)
- Voltaje de Entrada / Salida: 3.3V
- SoC: ESP32
- CPU principal: Tensilica Xtensa 32-bit LX6
- Frecuencia de Reloj: hasta 240Mhz
- Desempeño: Hasta 600 DMIPS
- WiFi: 802.11 b/g/n/e/i
- Bluetooth:v4.2 BR/EDR y Bluetooth Low Energy (BLE)
- Pines Digitales GPIO: 24 (Algunos pines solo como entrada)
- Convesor Analogolico Digital
- UART: 2
- Chip USB-Serial: CP2102
- Antena en PCB
- 38 PINES
- DIMENSIONES: 48 x 25,5 mm (Largo y Ancho)

Seguridad:
- Estandares IEEE 802.11: WFA, WPA/WPA2 y WAPI
- 1024-bit OTP
- Aceleracion criptográafica por hardware: AES, HASH (SHA-2), RSA, ECC, RNG

Memorias:
- 448 KByte ROM
- 520 KByte SRAM
- 16 KByte SRAM in RTC
QSPI Flash/SRAM, 4 MBytes

Contenido del paquete:
- 1 NodeMcu ESP-32S-WROOM Bluetooth + WiFi Linea Premium
